function init(self)
	msg.post(".","acquire_input_focus")
end

function final(self)
	msg.post(".","release_input_focus")
end

function on_input(self, action_id, action)
	if action.pressed and gui.pick_node(gui.get_node("Play"), action.x, action.y) then
		msg.post("main:/controller", "game")
		print("hey")
	elseif action.pressed and gui.pick_node(gui.get_node("Exit"), action.x, action.y) then
		os.exit()
	end
end